<?php

$this->breadcrumbs = array(
    'FS Analytics' => array('fsOffered'),
    'Manage',
);

echo '<h1>FS Offered List</h1>';

$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id' => 'fs-offered-form',
    'type' => 'horizontal',
    'enableAjaxValidation' => true,
    'htmlOptions' => array(
        'class' => 'well'
    ),
    'clientOptions' => array(
        'validateOnSubmit' => true
    )
));

echo $form->errorSummary($fsOfferedForm);

echo '<div class="row-fluid">';
echo '<div class="span6">';

echo $form->dropDownListRow($fsOfferedForm, 'states', CHtml::listData(GeogStates::model()->findAll(array('select' => 'abbr, abbr')), 'abbr', 'abbr'), array(
    'multiple' => true,
    'size' => '15',
    'hint' => 'Hold down CTRL to select multiple types.'
));

echo '</div>';
echo '<div class="span6">';

echo $form->datepickerRow($fsOfferedForm, 'responseEnrolledDate', array(
    'prepend' => '<i class="icon-calendar"></i>',
    'placeholder' => $fsOfferedForm->getAttributeLabel('responseEnrolledDate') . ' ...',
    'options' => array(
        'format' => 'yyyy-mm-dd',
        'autoclose' => true,
        'todayHighlight' => true
    ),
    'hint' => 'Any enrolled dates before this date with be included.'
));

echo $form->checkBoxRow($fsOfferedForm, 'includeResponseNotEnrolled');

echo '</div>';
echo '</div>';

echo '<p style="line-height: 18px; padding-bottom: 10px;">' .
    'The downloaded list is generated by the following criteria:' .
    '<ul style="font-family:line-height: 18px; padding-bottom: 10px;">' .
        '<li>USAA Policy</li>' .
        '<li>Active policy</li>' .
        '<li>States chosen Above</li>' .
        '<li>Email address exist</li>' .
        '<li>Response enrolled date before date listed above</li>' .
        '<li>Fireshield Status can be "offered" and can be "not enrolled"</li>' .
        '<li>PreRisk status can NOT be "enrolled" and can NOT "declined"</li>' .
        '<li>If selected above, response status of not enrolled will be included</li>' .
    '</ul>' .
'</p>';

echo CHtml::submitButton('Get List', array('class' => 'submit'));

$this->endWidget();
unset($form);